And2 schematics
sifferman/sky130_schematics pull request #12
Opened 2024-11-29 21:02 UTC by MitchTansey

2024-11-30 03:01 UTC, sifferman commented
Observe this error message:

> Please confirm your contribution by adding 'MitchTansey' to docs/CONTRIBUTORS in sorted order.
   If you do not wish to go by the name 'MitchTansey', update 'name=' in your ~/.gitconfig file.
   Also ensure your name on https://github.com/ under Settings->Profile->Name
   matches your ~/.gitconfig 'name=' field.

2024-11-30 04:16 UTC, sifferman commented
Just took a look at the cells. Thanks for your work!

Your 0 and 1 cells looks good.

Your 1 and 2 cells have a couple problems:

* There should not be any diagonal lines
* The inverters should all be facing the same direction.
* The inverters should probably all be stacked vertically. I don't see a reason to have them side by side, since there are a max of 4.

Feel free to take a look at the new nor2 cells for inspiration: <https://github.com/sifferman/sky130_schematics/releases/latest>

2024-12-04 00:44 UTC, MitchTansey commented
Ok, I implemented those changes, let me know if anything else needs reworking, thanks!

2024-12-04 02:08 UTC, sifferman commented
> Observe this error message:
> 
> > Please confirm your contribution by adding 'MitchTansey' to docs/CONTRIBUTORS in sorted order.
> > If you do not wish to go by the name 'MitchTansey', update 'name=' in your ~/.gitconfig file.
> > Also ensure your name on https://github.com/ under Settings->Profile->Name
> > matches your ~/.gitconfig 'name=' field.

Please implement this fix. Your name needs to be corrected in your .gitconfig and GitHub account. Then, you need to add your name to docs/CONTRIBUTORS

2024-12-04 02:19 UTC, sifferman requested changes
Also, if you pull from main, note this new error message your schematics get. You need to reorder the pins in your .sch files

> ERROR: .subckt definitions do not match between "netlists/and2/sky130_fd_sc_hd__and2_1.spice" and "references/and2/sky130_fd_sc_hd__and2_1.spice"
>  Expected: .subckt sky130_fd_sc_hd__and2_1 A B VGND VNB VPB VPWR X
>  Received: .subckt sky130_fd_sc_hd__and2_1 A X B VGND VNB VPB VPWR
>  Please reorder the ports inside "schematics/and2/sky130_fd_sc_hd__and2_1.sch"

2024-12-04 02:19 UTC, sifferman commented on schematics/and2/sky130_fd_sc_hd__and2_0.sch
> +C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
```suggestion
C {ipin.sym} -270 -100 0 0 {name=p1 lab=A}
C {ipin.sym} -270 -80 0 0 {name=p18 lab=B}
C {ipin.sym} -270 -60 0 0 {name=p19 lab=VGND}
C {ipin.sym} -270 -40 0 0 {name=p20 lab=VNB}
C {ipin.sym} -270 -20 0 0 {name=p21 lab=VPB}
C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
C {opin.sym} -200 -100 0 0 {name=p2 lab=X}
```

2024-12-04 02:19 UTC, sifferman commented on schematics/and2/sky130_fd_sc_hd__and2_1.sch
> +C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
```suggestion
C {ipin.sym} -270 -100 0 0 {name=p1 lab=A}
C {ipin.sym} -270 -80 0 0 {name=p18 lab=B}
C {ipin.sym} -270 -60 0 0 {name=p19 lab=VGND}
C {ipin.sym} -270 -40 0 0 {name=p20 lab=VNB}
C {ipin.sym} -270 -20 0 0 {name=p21 lab=VPB}
C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
C {opin.sym} -200 -100 0 0 {name=p2 lab=X}
```

2024-12-04 02:19 UTC, sifferman commented on schematics/and2/sky130_fd_sc_hd__and2_2.sch
> +C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
```suggestion
C {ipin.sym} -270 -100 0 0 {name=p1 lab=A}
C {ipin.sym} -270 -80 0 0 {name=p18 lab=B}
C {ipin.sym} -270 -60 0 0 {name=p19 lab=VGND}
C {ipin.sym} -270 -40 0 0 {name=p20 lab=VNB}
C {ipin.sym} -270 -20 0 0 {name=p21 lab=VPB}
C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
C {opin.sym} -200 -100 0 0 {name=p2 lab=X}
```

2024-12-04 02:19 UTC, sifferman commented on schematics/and2/sky130_fd_sc_hd__and2_4.sch
> +C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
```suggestion
C {ipin.sym} -270 -100 0 0 {name=p1 lab=A}
C {ipin.sym} -270 -80 0 0 {name=p18 lab=B}
C {ipin.sym} -270 -60 0 0 {name=p19 lab=VGND}
C {ipin.sym} -270 -40 0 0 {name=p20 lab=VNB}
C {ipin.sym} -270 -20 0 0 {name=p21 lab=VPB}
C {ipin.sym} -270 0 0 0 {name=p22 lab=VPWR}
C {opin.sym} -200 -100 0 0 {name=p2 lab=X}
```

2024-12-05 03:08 UTC, MitchTansey commented
ok i added myself to the contributors and everything, i also committed all your suggested changes. for some reason, it says that changes are still requested which I'm not sure about

2024-12-05 03:09 UTC, sifferman commented
I'll recommend changing your name to "Mitch Tansey". Please go through the process to do that

2024-12-05 03:09 UTC, sifferman approved these changes

2024-12-05 03:23 UTC, MitchTansey commented
well im confused because my .gitconfig has to match my username on github, but sean put they're name in the CONTRIBUTORS when their github username is not sean li

2024-12-05 03:26 UTC, sifferman commented
Yes, this is the contents of my `"~/.gitconfig"`
```gitconfig
[user]
	name = Ethan Sifferman
	email = ethan@sifferman.dev
```

2024-12-05 03:44 UTC, MitchTansey commented
Ok I changed it

2024-12-05 04:08 UTC, sifferman commented
You should also change your name on GitHub

2024-12-05 04:17 UTC, MitchTansey commented
I see ok I changed my name on github to "Mitchell Tansey"

2024-12-05 04:23 UTC, MitchTansey commented
Is there a way to run the checks again without committing anything? Because nothing needs to be changed in my actual repo, it was just a github thing

2024-12-05 04:26 UTC, merged

2024-12-05 04:29 UTC, sifferman commented
You're all set! Thanks for your work!

Note that I squashed this PR. So for your next branch, you will need to reset your git branch back to my main branch. Otherwise, you will get weird errors